### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by buke-dev** [everettjf/SpaceVimTutorial#1]
请问
对于MacVim，安装后在配置文件中加入：let g:spacevim_guifont='Knack\ Nerd\ Font:h12'
这句话的配置是加在哪个配置文件里面?
我尝试了许多次,但是都没有生效

**Comment by everettjf** [comment]
```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```

需要先安装这个。

配置文件是 `~/.SpaceVim.d/init.vim`

**Comment by buke-dev** [comment]
首先非常感谢您的回复:
![image](https://user-images.githubusercontent.com/24424535/41541579-5f99113a-7345-11e8-8f09-a7ada366004f.png)
我在终端安装完成后:
![image](https://user-images.githubusercontent.com/24424535/41541628-819b6ed6-7345-11e8-976b-5990f7a32eb7.png)
字体库安装的是hack-nerd-font并不是'Knack\ Nerd\ Font:h12' 而且
没有'Knack\ Nerd\ Font:h12'这个字体 这让我很困惑.
而且我的根目录也非常奇怪 在home目录下.SpaceVim.d文件夹内并没有init.vim只有init.toml
但是在~/SpaceVim/.SpaceVim.d/init.vim 这个路径是存在的
两个路径我都尝试过加入let g:spacevim_guifont='Knack\ Nerd\ Font:h12'这句话  都没有生效
我尝试将'Knack\ Nerd\ Font:h12'修改成'Hack\ Nerd\ Font:h12'也并没有生效
最后唯一尝试生效的是在文件上方工具栏切换字体成系统中的Hack\ Nerd\ Font字体生效并可以
正确显示了 但是每次打开软件都会重新恢复默认值,请问有什么建议可以给到我这边吗?非常感谢

**Comment by buke-dev** [comment]
非常感谢,我已经解决了这个问题 我用工具栏切换字体成正确字体后:set guifont=*命令，打开字体设置窗口，选择对应字体，发现，确认，然后用:echo &guifont命令看对应的值，将这个值写到用户配置，转义空格之后成功设置了字体, 最后还是非常感谢你的回复和帮助.
